In [5]:
#Import Libraries
import pandas as pd #Handling the Dataframe 
import numpy as np # For Calculations

In [6]:
#Task1 Employee Dataframe
emp = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30]})

In [7]:
#Seniorty Level Dataframe
seniority = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3]})

In [8]:
#Project Dataframe (notice missing costs)
project = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]})

In [9]:
#Save CSV 
emp.to_csv("Employee.csv", index=False)
seniority.to_csv("Seniority.csv", index=False)
project.to_csv("Project.csv", index=False)

In [10]:
#Task 2 Fill Missing Cost with Running Average
proj = pd.read_csv("Project.csv") # Reading Project CSV file

running_sum = 0 # Initializing running sum
count = 0 # Initializing count of valid values

for i in range(len(proj)): # Looping through each row
    if not pd.isna(proj.loc[i, "Cost"]):
        running_sum += proj.loc[i, "Cost"]
        count += 1
    else:
        proj.loc[i, "Cost"] = running_sum / count
proj.head(10)  # Replacing missing cost with running average

     ID     Project          Cost    Status
0  A001   Project 1  1.002000e+06  Finished
1  A002   Project 2  2.000000e+06   Ongoing
2  A003   Project 3  4.500000e+06  Finished
3  A004   Project 4  5.500000e+06   Ongoing
4  A005   Project 5  3.250500e+06  Finished
5  A002   Project 6  6.800000e+05    Failed
6  A005   Project 7  4.000000e+05  Finished
7  A003   Project 8  3.500000e+05    Failed
8  A001   Project 9  2.061714e+06   Ongoing
9  A003  Project 10  3.000000e+05  Finished

In [11]:
#Task 3 Split Name Column 
emp = pd.read_csv("Employee.csv")

emp[["First Name","Last Name"]] = emp["Name"].str.split(" ", expand=True) # Splitting Name column into First and Last name
emp.drop("Name", axis=1, inplace=True) # Dropping original Name column
emp.head()

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [12]:
#Task 4 Merge all the Dataframe
final = pd.merge(emp, seniority, on="ID") # Merging employee and seniority data
final = pd.merge(final, proj, on="ID") # Merging above result with project data
final.head()

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed

In [13]:
#Task 5 Add 5% Bonus for Finished Projects
final["Bonus"] = np.where(final["Status"]=="Finished", final["Cost"]*0.05, 0) # Creating Bonus column (5% of cost for Finished projects)
final[["First Name","Project","Status","Cost","Bonus"]].head()

  First Name     Project    Status          Cost    Bonus
0       John   Project 1  Finished  1.002000e+06  50100.0
1       John   Project 9   Ongoing  2.061714e+06      0.0
2       John  Project 11    Failed  2.000000e+06      0.0
3      Alice   Project 2   Ongoing  2.000000e+06      0.0
4      Alice   Project 6    Failed  6.800000e+05      0.0

In [14]:
#Task 6 Demote 
final.loc[final["Status"]=="Failed","Designation Level"] += 1 # Increasing designation level by 1 for failed projects
final = final[final["Designation Level"] <= 4] # Removing employees with designation level above 4
final[["First Name","Status","Designation Level"]].head()

  First Name    Status  Designation Level
0       John  Finished                  2
1       John   Ongoing                  2
2       John    Failed                  3
3      Alice   Ongoing                  2
4      Alice    Failed                  3

In [15]:
#Task 7 Mr./Mrs. & Drop Gender 
final["First Name"] = np.where(final["Gender"]=="M","Mr. "+final["First Name"],"Mrs. "+final["First Name"]) # Adding Mr. or Mrs. based on gender
final.drop("Gender", axis=1, inplace=True) # Dropping Gender column
final.head()

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0

In [16]:
#Task 8 promote if age>29 
final.loc[final["Age"]>29,"Designation Level"] -= 1 # Reducing designation level by 1 for age greater than 29
final[["First Name","Age","Designation Level"]].head()

   First Name  Age  Designation Level
0    Mr. John   25                  2
1    Mr. John   25                  2
2    Mr. John   25                  3
3  Mrs. Alice   27                  2
4  Mrs. Alice   27                  3

In [17]:
#Task 9 Total Project Cost per Employee 
total_cost = final.groupby(["ID","First Name"])["Cost"].sum().reset_index() # Grouping by ID and First Name and summing cost
total_cost.rename(columns={"Cost":"Total Cost"}, inplace=True) # Renaming column
total_cost

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [19]:
#Task 10 City Contains letter "o"
result = final[final["City"].str.contains("o", case=False)] # Filtering employees where city contains letter 'o'
result # Displaying result

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000.0